version: '3'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'bholder_ch_ph'
    ports:
      - '3306:3306'
# version: '3'

# services:
#   bholder_db:
#     container_name: mongo_bholder
#     image: mongo
#     restart: always
#     ports:
#       - '27017:27017'
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: bholder_ch_ph
